### ISSUE TITLE
Linking CPR resolves to linker errors (VS19)

### ISSUE THREAD

**Issue by oofsamy** [libcpr/cpr#702]
## Description

I'm trying to build a plugin that uses BMSDK (BakkesmodSDK), and I am linking this library as I usually use it for every C++ project of mine that has required http requests, but upon building I came across a lot of linker errors, as shown below, I've tried the first 5, 6 solutions I've seen (most were the same, to just set the "RuntimeLibrary" to "Multi-threaded", though it was already on that setting), so I'm assuming it's something to do with the way the library was built

## Expected Behavior
Build with no linker errors

## Actual Behavior
Didn't build and had linker errors

## Possible Fix

No idea, I'm a C++ noob

## Steps to Reproduce

1.Make a bakkesmod plugin via the template
2.Link this library
3.Watch the errors commence

## Context

Not much since this was just a side project to distract me from my main

## Your Environment

* Version used: Not sure how to check, sorry :(
* Where did you get it from (e.g. conan, vcpkg, master, ...): Installed via vcpkg by running the following command `vcpkg.exe install cpr:x64-windows`
* Operating System and version: Windows 10 Pro (21H1)
* Link to a small example: ![image](https://user-images.githubusercontent.com/61066276/153060445-1f686794-7347-41e2-bc64-1c9102887af9.png)

Sorry if waste of issue, linking libraries has never been fun for me

**Comment by COM8** [comment]
Looks to me like you try to link a shared version of `cpr` to your static project.
Try to install `cpr:x64-windows-static` and link against this one.

Regarding linking on Windows: This is always a pain since there is no general location on Windows, where you can store libraries like on Linux. Also VS obscures all of this even more. While this might be fine for small projects, it's a hassle for larger ones using multiple compilation units. I then always use CMake to get around this since VS has build in support for it.

**Comment by COM8** [comment]
Closing since no response.
