### ISSUE TITLE
Range request support

### ISSUE THREAD

**Issue by dwbuiten** [libcpr/cpr#75]
Can't find anything about support for this in the options, or docs.

Doable via CURLOPT_RANGE.

**Comment by whoshuu** [comment]
Thanks for the suggestion @dwbuiten!

[Official documentation](https://curl.haxx.se/libcurl/c/CURLOPT_RANGE.html) for `CURLOPT_RANGE`.

- [ ] Tests
- [ ] Implementation
- [ ] Documentation

A reasonable implementation of this could be to create a `Range` object that supports both `start` and `end` explicitly, or just `start` explicitly so that the `end` is assumed to be the end of the response . Marking this as easy since it has no memory implications and is limited in scope. The implementation should use unsigned long as the integer type, and a boolean to indicate whether `start` and `end` were specified or just `end`.

Note that this does not yet allow for multiple ranges to be supported in the form `"X-Y,N-M"`. That can be tackled in the future with a container object that is constructed from multiple ranges.

**Comment by dwbuiten** [comment]
I would rather discourage use of `long` in 2015, which would limit ranges to 4gb. Since this is a C++11 project, you'd probably want to use `uint64_t`.

**Comment by whoshuu** [comment]
Good point @dwbuiten , I'll make an edit on my implementation comment about that.

**Comment by simon-berger** [comment]
I intend to work on this issue within the next half year. Would be happy if I can be assigned to the issue

**Comment by COM8** [comment]
#701 already added basic support for it, but feel free to extend it further.
