### ISSUE TITLE
cprver.h

### ISSUE THREAD

**Issue by Blackqx0** [libcpr/cpr#811]
![image](https://user-images.githubusercontent.com/102927513/185283643-15e8593e-3fce-46dd-92e0-ccc92ca1291e.png)
so i tried cloning the library but i always get that problem, whats the solution?

**Comment by COM8** [comment]
`cprver.h` ist generated during the build process using CMake based on [this](https://github.com/libcpr/cpr/blob/master/cmake/cprver.h.in) file.

For the next time, please use the issue template since I don't know how you are integrating cpr, what OS you are on and what version of cpr you are using.

**Comment by Blackqx0** [comment]
thank you. my bad <3.
