### ISSUE TITLE
Can the author provide static library of libcpr under windwos msvc?

### ISSUE THREAD

**Issue by 0x6C696A756E** [libcpr/cpr#975]
### Is your feature request related to a problem?

Can the author provide static library of libcpr under windwos msvc?

### Possible Solution

Can the author provide static library of libcpr under windwos msvc?

**Comment by COM8** [comment]
I'm not 100% sure what you want. If you just want a static file containing the library you have a couple of options:
* Build it yourself: 
```
git clone https://github.com/libcpr/cpr.git
cd cpr && mkdir build && cd build
cmake .. -DBUILD_SHARED_LIBS=OFF
cmake --build . --parallel
# Find your static files
```

* Use vcpkg: https://github.com/libcpr/cpr#building-cpr---using-vcpkg
* USe conan: https://github.com/libcpr/cpr#building-cpr---using-conan

For all you further issues I suggest being a bit more elaborate when describing your situation/request.

**Comment by Nolram12345** [comment]
Building libraries that way does create static libraries, but they still use the DLL runtime. I tried building the binaries using /Mt (and /Mtd for debug), but that results in all kinds of other linking issues when trying to use them in a project.

**Comment by COM8** [comment]
As far as I understand `/MD` just indicates whether the runtime lib will be a custom DLL, so still dynamic library.

Based on the vcpkg docs, static linking is easy: https://devblogs.microsoft.com/cppblog/vcpkg-updates-static-linking-is-now-available/

Sorry, I think this is not a cpr issue and more a how do I tell msvc to do the right thing here. Sadly I can't really help you with that since I mostly have experience with gcc and clang, not msvc.

**Comment by Nolram12345** [comment]
I was talking about /Mt, not /MD. The problem is that DLLs built for DLL-based CRT runtime environments aren't compatible with embedded ones in some cases, like here with CPR. 
VCPKG does build ones for using embedded CRT as well, but not everyone is using VCPKG :/ So it would be good to provide builds for this too.

**Comment by COM8** [comment]
OK, but then it's a vcpkg issue. We do not maintain the vcpkg package.

As an alternative in your project set the appropriate CMAKE options when compiling cpr on your own.

**Comment by Nolram12345** [comment]
No, it's not a VCPKG issue? The problem is that your static libs CMAKE option does build the library as static, but does still use the DLL version of the C runtime on Windows. That's why builds with the /Mt (and debug version of that flag) are so important because otherwise it's impossible to use CPR when using an embedded C runtime. 
[See the MSVC docs for more info](https://learn.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=msvc-170)

**Comment by GsoyG** [comment]
I encountered a similar problem and found a solution in curl's issues. Might be helpful to you.

The reason is probably because curl under the Windows platform calls the Win32 API. If you statically link curl, you must also statically link the library where the Win32 API is located. This does not happen automatically, so the Win32 API symbols cannot be found.

**Solution: In the project properties of VS, Linker-Input-Additional Dependencies. Add the following four static library names:**

```
WS2_32.Lib
Wldap32.Lib
Crypt32.Lib
Normaliz.lib
```
